import React, { useState } from 'react';
import { Form, Loader, Card } from '../components';

type Props = {
  data: any;
  title: string;
};

const RenderCards: React.FC<Props> = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post: any) => <Card key={post.id} {...post} />);
  }

  return (
    <h2 className="mt-5 font-bold text-[#37A051] text-xl uppercase">{title}</h2>
  );
};
export const HomePage: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [searchText, setSearchText] = useState('');
  const [allPosts, setAllpost] = useState(null);

  return (
    <>
      <section className="bg-[#181818] min-h-54 py-[50px] px-[10px]">
        <div className=" max-w-[1200px] mx-auto ">
          <h1 className="font-bold text-[32px] ">Showcase</h1>
          <p className="mt-2 text-[20px] max-w-[1000px] text-[#babec4]">
            Browse through a collection of imaginative and visually stunning
            images generated by DALL-E AI
          </p>
          <div className="mt-16">
            <Form />
          </div>
        </div>
      </section>
      <section className="mt-10  max-w-[1200px] mx-auto">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <div>
            {searchText && (
              <h2 className="font-medium text-[#babec4] text-xl mb-3">
                Showing results for&nbsp;
                <span className="text-[#fff]">{searchText}</span>
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards data={[]} title="No search results found" />
              ) : (
                <RenderCards data={[]} title="No posts found" />
              )}
            </div>
          </div>
        )}
      </section>
    </>
  );
};
